version: "3"

services:
  web:
    image: ${PROJECT}-${ENV}:app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always