version: "3"

services:
  web:
    image: punkerside-api:web
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongo
  mongo:
    image: punkerside-api:db